version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=person
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"

  web:
    container_name: GRPC
    build: 
      context: .
    ports:
      - "50051:50051"
    environment:
      - POSTGRES_DB_URL=postgres://postgres:123@postgres:5432/person?sslmode=disable
    depends_on:
      - postgres